apiRules:
- include:
    uidRegex: ^com\.nickmaltbie\.ScreenManager
    type: Namespace
- include:
    uidRegex: ^com\.nickmaltbie\.ScreenManager\.*
    type: Namespace
- exclude:
    uidRegex: .*
    type: Namespace