name: Build Verification

on:
  pull_request:

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE_2021_1 }}

jobs:
  buildForSomePlatforms:
    name: Build for ${{ matrix.targetPlatform }} on version ${{ matrix.unityVersion }}
    runs-on: Ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        unityVersion:
          - 2021.1.19f1
        targetPlatform:
          - WebGL
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/git-lfs-cache
      - uses: ./.github/workflows/unity-library-cache
        with:
          runner_os: ${{ runners.os }}
          target_platform: ${{ matrix.targetPlatform }}

      - uses: game-ci/unity-builder@v2.0-alpha-13
        with:
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          buildMethod: ScriptBatch.TestBuild_${{ matrix.targetPlatform }}
