name: Code and Docs Lint

# Controls when the action will run. Triggers the workflow on push or pull request
on:
  pull_request:
  push:
    branches:
      - main

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE_2021_1 }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  code-format:
    name: Dotnet code validation
    runs-on: Ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        unityVersion:
          - 2021.1.19f1
        targetPlatform:
          - WebGL

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/git-lfs-cache
      - uses: ./.github/workflows/unity-library-cache
        with:
          runner_os: ${{ runners.os }}
          target_platform: ${{ matrix.targetPlatform }}

      - name: Ensure .sln file is generated
        uses: game-ci/unity-builder@v2.0-alpha-13
        with:
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          buildMethod: Packages.Rider.Editor.RiderScriptEditor.SyncSolution

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"

      # Restore dotnet tools. This handles cache implicitly.
      - run: dotnet tool restore

      - name: Format C# Code
        run: dotnet format workspace.sln --severity warn --verbosity detailed --exclude --exclude Library --verify-no-changes

      - name: Format C# Whitespace
        run: dotnet format whitespace workspace.sln --verbosity detailed --exclude Library --verify-no-changes

  lint-markdown:
    name: Lint markdown files
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Lint Markdown Files
      uses: avto-dev/markdown-lint@v1
      with:
        args: '.'

  # Build the documentation
  docfx-check:
    name: DocFx documentation validation
    runs-on: windows-latest # Required by DocFX
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/git-lfs-cache

      - name: Install DocFX
        run: choco install -y docfx

      - name: Build Website
        run: .\Documentation\build.cmd
