name: Git Large File Storage Cache Reusable Workflow

on:
  workflow_call:

jobs:
  git-lfs-cache:
    name: Setup the git-lfs Cache
    runs-on: ubuntu-latest
    steps:
      - name: Create LFS file list
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id

      - name: Cache git lfs
        uses: actions/cache@v2
        with:
          path: .git/lfs
          key: lfs-format-${{ hashFiles('.lfs-assets-id') }}-v1.0.0
          # use previous cache if current one is not found
          restore-keys: |
            lfs-format-

      - name: Pull lfs data, if not cached
        run: git lfs pull
